# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6abc00d28724c25028c413a2884c276413867752070e1ed9fd1087525c97d6cc673cd5ab2f7e9b14434e395b08500448c93c9781e62925341631fd7af17a3939

test:
  secret_key_base: f5caf94c0b8397fa1b14c0b23473f59591a2bb1cc12a9c07808f344fab9b51e470ecab366aed55bf2a59cf365a9a170488bc57fa855b216e8d9cf715df9a53c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
